config/routes.rb
Rails.application.routes.draw do
  get 'privacy_policy/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'top#index'
  get "/privacy_policy" => "privacy_policy#index"

  resources :login, only: [:new, :create]
  delete '/logout',  to: 'login#destroy'
  
  resources :stores, except: [:index] do
    post 'approve_staff/:user_id', action: 'approve_staff'
    resources :store_weekly_schedules, only: [:new, :create, :destroy]
    resources :store_month_schedules, only: [:index, :create, :destroy] do
      collection do
        get ':beginning/new', action: 'new'
      end
    end
    
    resources :shift_section, only: [:index, :new, :create, :destroy]
    resources :shifts, only: [:create, :destroy] do
      collection do
        post ':beginning/change_status/:status' => 'shift_section#change_status'
        get ':beginning/:ending/new', action: 'new'
        get ':date/:working_time_from/edit', action: 'edit'
        get ':beginning', action: 'index'
      end
    end
  end

  resources :users, only: [:show, :new, :create, :edit, :update] do
    resources :user_weekly_schedules, :user_unable_schedules, :affiliation_application, only: [:new, :create, :destroy]
    resources :user_unable_schedules, only: [:index, :create, :destroy] do
      collection do
        get ':beginning/new', action: 'new'
      end
    end
    resources :user_submissions, only: [:create, :destroy]
  end
end

app/models/store_month_schedule.rb
class StoreMonthSchedule < ApplicationRecord
  include CalendarHelper
  belongs_to :store

  with_options presence: true do
    validates :store_id
    validates :date
    validates :working_time_from
    validates :working_time_to
    validates :count
  end
  validates :working_time_from, uniqueness: {scope: [:store_id, :date]}
  validates :working_time_to, uniqueness: {scope: [:store_id, :date]}
  validate :working_time, :shift_section, :duplicate

  def working_time
    if working_time_from && working_time_to
      if working_time_from >= working_time_to
        errors.add(:working_time_from, "可能な時間に設定してください")
      end
    end
  end

  def shift_section
    if working_time_from && working_time_to
      shift_sections = ShiftSection.where(store_id: store_id, status: 0)
      shift_section = shift_sections.find {|shift_section| date.between?(shift_section.beginning, shift_section.ending)}
      if shift_section.nil?
        errors.add(:date, "期間内の日付を設定してください。")
      end
    end
  end

  def duplicate
    if working_time_from && working_time_to
      current_user_store = Store.find_by(id: store_id)
      store_schedule_dates = current_user_store.store_month_schedules.where(date: date)
      store_schedule_dates&.each do |store_schedule_date|
        if for_model_duplicate?(store_schedule_date)
          errors.add(:date, "重複しています。可能な時間を設定するか、スケジュールを削除してからもう一度登録してください。")
        end
      end
    end
  end
end

app/controllers/store_month_schedules_controller.rb
class StoreMonthSchedulesController < ApplicationController
  before_action :logged_in_user, :store_staff, except: [:create, :destroy]
  before_action :owner_permission, only: [:create, :destroy]
  before_action :store_independent
  include CalendarHelper
  helper_method :date_table

  include ActiveModel::Attributes
  include ActiveRecord::AttributeAssignment
  attribute :date, :date

  def store_month_schedule_params
    params.require(:store_month_schedule).permit(:date, :working_time_from, :working_time_to, :count, :store_id).merge(store_id: @current_user.store.id)
  end

  def new
    @store = Store.find(params[:store_id])
    @store_month_schedule = StoreMonthSchedule.new
    @store_shift_section = ShiftSection.find_by(store_id: params[:store_id], beginning: params[:beginning])
  end

  def index
    @store = Store.find(params[:store_id])
    @store_shift_sections = ShiftSection.where(store_id: params[:store_id])
  end
  
  def create
    @store = Store.find(params[:store_id])
    @store_month_schedule = StoreMonthSchedule.new(store_month_schedule_params)
    @store_shift_section = ShiftSection.find_by(store_id: params[:store_id], beginning: params[:beginning])
    if @store_month_schedule.save
      redirect_to "/stores/#{params[:store_id]}/store_month_schedules/#{params[:beginning]}/new"
    else
      render :new
    end
  end
  def destroy
    StoreMonthSchedule.destroy(params[:id])
    redirect_to new_store_store_month_schedule_path
  end
end

app/helpers/store_month_schedules_helper.rb
module StoreMonthSchedulesHelper
end

app/views/store_month_schedules/index.html.erb
<h1>ストアスケジュール一覧</h1>
<% @store_shift_sections.each do |store_shift_section| %>
  <%= link_to "#{store_shift_section.beginning}~#{store_shift_section.ending}", "/stores/#{params[:store_id]}/store_month_schedules/#{store_shift_section.beginning}/new" %>
  <br>
<% end %>
<%= link_to '1週間設定',  new_store_store_weekly_schedule_path(@store) %><br>

app/views/store_month_schedules/new.html.erb
<%= link_to '1週間設定',  new_store_store_weekly_schedule_path(@store) %><br>
<% if owner? && @store_shift_section.status == 0 %>
  <% @store_month_schedule.errors.full_messages.each do |message| %>
    <div class="form-error">
      <%= message %>
    </div>
  <% end %>
  <%= form_for [@store, @store_month_schedule], url: "/stores/#{params[:store_id]}/store_month_schedules?beginning=#{params[:beginning]}" do |f| %>
    <%= f.date_select :date, {use_month_numbers: true} %>
    <h1>時間</h1>
    <div class="time">
      <%= f.time_field :working_time_from, class: "working_time" %>
      <p>〜</p>
      <%= f.time_field :working_time_to, class: "working_time" %>
      <h1>人数</h1>
      <%= f.number_field :count, min: 1 %>
      <%= f.submit "追加" %>
    </div>
  <% end %>
  <br>
  <%= button_to 'スケジュールを決定', "/stores/#{params[:store_id]}/shifts/#{params[:beginning]}/change_status/1" %>
<% end %>

<%= SimpleCalendar::BusinessWeekCalendar.new(self, {}).render do |date| %>
  <%= date.day %>
  <table>
    <% date_working_times(date).each do |dwt| %>
      <tr>
        <td><%= dwt.working_time_from.strftime( "%H:%M" ) %></td>
        <td rowspan="2">
          <%= dwt.count %>人
          <% if dwt[:date] != nil && owner? && @store_shift_section.status == 0  %>
            <%= button_to '削除', store_store_month_schedule_path(@store, dwt), method: :delete %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td><%= dwt.working_time_to.strftime( "%H:%M" ) %></td>
      </tr>
    <% end %>
  </table>
<% end %> 