config/routes.rb
Rails.application.routes.draw do
  get 'privacy_policy/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'top#index'
  get "/privacy_policy" => "privacy_policy#index"

  resources :login, only: [:new, :create]
  delete '/logout',  to: 'login#destroy'
  
  resources :stores, except: [:index] do
    post 'approve_staff/:user_id', action: 'approve_staff'
    resources :store_weekly_schedules, only: [:new, :create, :destroy]
    resources :store_month_schedules, only: [:index, :create, :destroy] do
      collection do
        get ':beginning/new', action: 'new'
      end
    end
    
    resources :shift_section, only: [:index, :new, :create, :destroy]
    resources :shifts, only: [:create, :destroy] do
      collection do
        post ':beginning/change_status/:status' => 'shift_section#change_status'
        get ':beginning/:ending/new', action: 'new'
        get ':date/:working_time_from/edit', action: 'edit'
        get ':beginning', action: 'index'
      end
    end
  end

  resources :users, only: [:show, :new, :create, :edit, :update] do
    resources :user_weekly_schedules, :user_unable_schedules, :affiliation_application, only: [:new, :create, :destroy]
    resources :user_unable_schedules, only: [:index, :create, :destroy] do
      collection do
        get ':beginning/new', action: 'new'
      end
    end
    resources :user_submissions, only: [:create, :destroy]
  end
end

app/models/store_schedule.rb
class StoreSchedule < ApplicationRecord
  belongs_to :store
  # belongs_to :Weeklyday

  with_options presence: true do
    validates :store_id
    validates :weeklyday_id
    validates :working_time_from
    validates :working_time_to
    validates :count
  end
  validates :working_time_from, uniqueness: { scope: [:working_time_to, :working_time_from, :store_id, :weeklyday_id] }
  validates :working_time_to, uniqueness: { scope: [:working_time_from, :working_time_from, :store_id, :weeklyday_id] }
  validate :working_time, :duplicate

  def working_time
    if working_time_from && working_time_to
      if working_time_from > working_time_to
        errors.add(:working_time_from, "可能な時間に設定してください")
      end
    end
  end

  def duplicate
    if working_time_from && working_time_to
      current_user_store = Store.find_by(id: store_id)
      store_schedule_weeklydays = current_user_store.store_schedules.where(weeklyday_id: weeklyday_id)
      store_schedule_weeklydays.each do |store_schedule_weeklyday|
        if store_schedule_weeklyday.working_time_from < working_time_from && working_time_from < store_schedule_weeklyday.working_time_to || \
          store_schedule_weeklyday.working_time_from < working_time_to && working_time_to < store_schedule_weeklyday.working_time_to
          errors.add(:weeklyday_id, "重複しています。可能な時間を設定するか、スケジュールを削除してからもう一度登録してください。")
        end
      end
    end
  end
end

app/controllers/store_schedules_controller.rb
class StoreSchedulesController < ApplicationController
  before_action :logged_in_user, :store_staff, except:[:crate, :destroy]
  before_action :owner_permission, only: [:crate, :destroy]
  before_action :store_independent
  helper_method :bar_line, :calendar_wday

  def storeSchedule_params
    params.require(:store_schedule).permit(:working_time_from, :working_time_to, :count, :store_id, weeklyday_id: []).merge(store_id: @current_user.store.id)
  end

  def weekly_scheduled
    @working_times = []
    StoreSchedule.where(store_id: params[:store_id]).each do |store_schedule|
      @working_times.push(store_schedule.working_time_from)
      @working_times.push(store_schedule.working_time_to)
    end
    if @working_times.count > 2
      @working_times.uniq!
      @working_times.sort!
    end
    @weeklydays = Weeklyday.all
    def bar_line(weeklyday, working_time)
      store_schedules = StoreSchedule.where(weeklyday_id: weeklyday, store_id: params[:store_id])
      store_schedules.each do |store_schedule|
        if store_schedule.working_time_from < working_time && working_time < store_schedule.working_time_to
          return true
          break
        end
      end
      return false
    end
  end

  def new
    @store = Store.find(params[:store_id])
    @store_schedule = StoreSchedule.new
    weekly_scheduled
    @store_month_schedule = StoreMonthSchedule.new
  end
  
  def create
    @store = Store.find(params[:store_id])
    @store_schedule = StoreSchedule.new
    weekly_scheduled
    if params[:store_schedule][:weeklyday_id]
      params[:store_schedule][:weeklyday_id].each do |weeklyday_id|
        @store_schedule = StoreSchedule.new(storeSchedule_params.merge(weeklyday_id: weeklyday_id))
        @store_schedule.save
      end
      if @store_schedule.save
        redirect_to new_store_store_schedule_path
      else
        render :new
      end
    else
      @store_schedule = StoreSchedule.create(storeSchedule_params)
      render :new
    end
    
    @store_month_schedule = StoreMonthSchedule.new
  end
  
  def destroy
    StoreSchedule.destroy(params[:id])
    redirect_to new_store_store_schedule_path
  end

  def update
  end

end

app/views/store_schedules/_weekly_scheduled.html.erb
<table class="table weekly_scheduled">
  <tr>
    <th></th>
    <th>月曜日</th>
    <th>火曜日</th>
    <th>水曜日</th>
    <th>木曜日</th>
    <th>金曜日</th>
    <th>土曜日</th>
    <th>日曜日</th>
  </tr>
  <% @working_times.each_with_index do |working_time, i| %>
    <tr>
      <th><%= working_time.strftime( "%H:%M" ) %></th>
      <% @weeklydays.each do |weeklyday| %>
          <%  working_time_from_weeklyday = StoreSchedule.find_by(working_time_from: working_time, weeklyday_id: weeklyday.id, store_id: params[:store_id]) %>
          <%  working_time_to_weeklyday = StoreSchedule.find_by(working_time_to: working_time, weeklyday_id: weeklyday.id, store_id: params[:store_id]) %>
          <% if working_time_from_weeklyday && working_time_to_weeklyday %>
            <td>
              <%= "┿   #{working_time_from_weeklyday.count}人" %>
              <% if owner? %>
                <%= button_to '削除', store_store_schedule_path(@store, working_time_from_weeklyday), method: :delete %>
              <% end %>
            </td>
          <% elsif working_time_from_weeklyday %>
            <td style="border-top:1px solid #1f1f1f;">
              <%= "┯	  #{working_time_from_weeklyday.count}人" %>
              <% if owner? %>
                <%= button_to '削除', store_store_schedule_path(@store, working_time_from_weeklyday), method: :delete %>
              <% end %>
            </td>
          <% elsif working_time_to_weeklyday %>
            <td style="border-bottom:1px solid #1f1f1f;">┷</td>
          <% elsif bar_line(weeklyday.id, working_time) %>
            <td>│</td>
          <% else %>
            <td></td>
          <% end %>
      <% end %>
    </tr>
  <% end %>
</table>