config/routes.rb
Rails.application.routes.draw do
  get 'privacy_policy/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'top#index'
  get "/privacy_policy" => "privacy_policy#index"

  resources :login, only: [:new, :create]
  delete '/logout',  to: 'login#destroy'
  
  resources :stores, except: [:index] do
    post 'approve_staff/:user_id', action: 'approve_staff'
    resources :store_weekly_schedules, only: [:new, :create, :destroy]
    resources :store_month_schedules, only: [:index, :create, :destroy] do
      collection do
        get ':beginning/new', action: 'new'
      end
    end
    
    resources :shift_section, only: [:index, :new, :create, :destroy]
    resources :shifts, only: [:create, :destroy] do
      collection do
        post ':beginning/change_status/:status' => 'shift_section#change_status'
        get ':beginning/:ending/new', action: 'new'
        get ':date/:working_time_from/edit', action: 'edit'
        get ':beginning', action: 'index'
      end
    end
  end

  resources :users, only: [:show, :new, :create, :edit, :update] do
    resources :user_weekly_schedules, :user_unable_schedules, :affiliation_application, only: [:new, :create, :destroy]
    resources :user_unable_schedules, only: [:index, :create, :destroy] do
      collection do
        get ':beginning/new', action: 'new'
      end
    end
    resources :user_submissions, only: [:create, :destroy]
  end
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :store
  belongs_to :user
end

app/models/store.rb
class Store < ApplicationRecord
  generate_public_uid generator: PublicUid::Generators::NumberRandom.new

  has_many :store_weekly_schedules, dependent: :destroy
  has_many :Weeklydays, through: :store_weekly_schedules
  has_many :users
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  has_many :store_month_schedules
  has_many :shift_sections, dependent: :destroy
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :store_staff, :store_independent, only: [:index]
  before_action :owner_permission, except: [:index]
  include CalendarHelper
  helper_method :date_table

  def index
    @store = Store.find(params[:store_id])
    @shift_section = ShiftSection.find_by(store_id: @store.id, beginning: params[:beginning])
    if @shift_section.status == 2 && !Shift.find_by(date: @shift_section.beginning..@shift_section.ending)
      shift_auto_allocation
    end
    @working_time_sum = {}
    @working_time_sum = {}
    @store.users.each do |user|
      if UserSubmission.find_by(user_id: user.id, shift_section_id: @shift_section.id)
        @working_time_sum.store(user.id, 0)
      end
    end
  end

  def edit
    @store = current_user.store
    @shifts = Shift.where(date: params[:date], working_time_from: params[:working_time_from])
    @date_available_staff = store_date_available_staffs(params[:date].to_date).find { |a| a[:date] == params[:date].to_date && a[:working_time_from].strftime( "%H:%M" ) == params[:working_time_from] }
    @submission_user = []
    @store_user = []
    @shift_section = ShiftSection.where(store_id: @store.id).find { |a| (a.beginning..a.ending).cover?(params[:date].to_date) }
    Store.find(params[:store_id]).users.each do |user|
      @store_user.push(user)
      if user.user_submissions.find_by(shift_section_id: @shift_section.id)
        @submission_user.push(user)
      end
    end
  end

  def destroy
    @store = Store.find(params[:store_id])
    @shift = Shift.find(params[:id])
    @shift.destroy
    redirect_to "/stores/#{@store.id}/shifts/#{@shift.date}/#{@shift.working_time_from.strftime( "%H:%M" )}/edit"
  end

  def create
    @store = Store.find(params[:store_id])
    @shift = Shift.new(
      store_id: @store.id,
      date: params[:date],
      working_time_from: params[:working_time_from],
      working_time_to: params[:working_time_to],
      user_id: params[:user_id]
    )
    @shift.save
    redirect_to "/stores/#{@store.id}/shifts/#{@shift.date}/#{@shift.working_time_from.strftime( "%H:%M" )}/edit"
  end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/edit.html.erb
<%= link_to "シフトに戻る", "/stores/#{params[:store_id]}/shifts/#{@shift_section.beginning}" %>
<h1><%= "#{params[:date]} #{params[:working_time_from]} ~ #{@date_available_staff[:working_time_to].strftime( "%H:%M" )}" %></h1>
<h2>勤務予定<%= "#{@date_available_staff[:count]}人" %>(クリックで削除)</h2>
<% unless @shifts.blank? %>
  <% @shifts.each do |shift| %>
    <%  working_user = User.find(shift.user_id) %>
    <%= link_to "#{working_user.name}",  store_shift_path(@store, shift), method: :delete %>
    <% @store_user.delete(working_user) %>
  <% end %>
<% end %>
<h2>勤務可能(クリックで追加)</h2>
<% unless @date_available_staff.blank? %>
  <% @date_available_staff[:user_ids].each do |id| %>
    <% available_staff = User.find(id) %>
    <% if @store_user.include?(available_staff) %>
      <%= link_to "#{available_staff.name}",  store_shifts_path(@store, date: @date_available_staff[:date], working_time_from: @date_available_staff[:working_time_from], working_time_to: @date_available_staff[:working_time_to], user_id: id), method: :post %>
      <% @store_user.delete(available_staff) %>
    <% end %>
  <% end %>
<% end %>
<h2>シフト提出済(クリックで追加)</h2>
<% unless @submission_user.empty? %>
  <% @submission_user.each do |su| %>
    <% if @store_user.include?(su) %>
      <%= link_to "#{su.name}",  store_shifts_path(@store, date: @date_available_staff[:date], working_time_from: @date_available_staff[:working_time_from], working_time_to: @date_available_staff[:working_time_to], user_id: su.id), method: :post %>
      <% @store_user.delete(su) %>
    <% end %>
  <% end %>
<% end %>
<h2>シフト未提出(クリックで追加)</h2>
<% unless @store_user.empty? %>
  <% @store_user.each do |su| %>
      <%= link_to "#{su.name}",  store_shifts_path(@store, date: @date_available_staff[:date], working_time_from: @date_available_staff[:working_time_from], working_time_to: @date_available_staff[:working_time_to], user_id: su.id), method: :post %>
  <% end %>
<% end %>

app/views/shifts/index.html.erb
<% content_for :viewport do %>
""
<% end %>
<%= link_to 'シフト一覧へ',  store_shift_section_index_path %><br>
<% if owner? %>
  <% if @shift_section.status == 2 %>
    <%= button_to '決定',  "/stores/#{params[:store_id]}/shifts/#{params[:beginning]}/change_status/3", method: :post %>
  <% elsif @shift_section.status == 3 %>
    <%= button_to '再編集',  "/stores/#{params[:store_id]}/shifts/#{params[:beginning]}/change_status/2", method: :post %>
  <% elsif @shift_section.status == 0 %>
    <%= link_to 'ストアスケジュール編集',  "/stores/#{params[:store_id]}/store_month_schedules/#{params[:beginning]}/new" %>
  <% elsif @shift_section.status == 1 %>
    <% @store.users.each do |member| %>
      <div>
        <%= member.name %>
        <% submission_user = UserSubmission.find_by(user_id: member.id, shift_section_id: @shift_section.id) %>
        <% if submission_user %>
          提出済
        <% else %>
          <font color="red">未提出</font>
        <% end %>
      </div>
    <% end %>
    <%= button_to 'シフト作成',  "/stores/#{params[:store_id]}/shifts/#{params[:beginning]}/change_status/2", method: :post %>
  <% end %>
<% else %>
  <% if @shift_section.status == 2 %>
    <p>オーナーが編集中</p>
  <% end %>
<% end %>
<%= SimpleCalendar::BusinessWeekCalendar.new(self, {}).render do |date| %>
  <div class="date">
    <%= date.day %>
    <table class="date_table">
      <% date_working_times(date).each do |dt| %>
        <% date_shifts = Shift.where(date: date, working_time_from: dt.working_time_from) %>
        <tr>
          <td class="shift_working_time"><%= dt.working_time_from.strftime( "%H:%M" ) %></td>
          <td rowspan="2">
            <%= "#{dt.count}人" %><br>
            <% date_shifts.each do |date_shift| %>
              <% working_user = User.find(date_shift.user_id) %>
              <% if current_user?(working_user) %>
                <font color="red"><%= working_user.name %></font>
              <% else %>
                <%= working_user.name %>
              <% end %><br>
              <% @working_time_sum[working_user.id] += dt.working_time_to - dt.working_time_from if @working_time_sum[working_user.id] %>
            <% end %>
            <% if owner? && @shift_section.status == 2 %>
              <%= link_to '編集',  "/stores/#{@store.id}/shifts/#{date}/#{dt.working_time_from.strftime( "%H:%M" )}/edit" %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td class="shift_working_time"><%= dt.working_time_to.strftime( "%H:%M" ) %></td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>
<table class="table working_time_sum">
  <tr>
    <th>名前</th>
    <th>勤務希望時間</th>
    <th>合計勤務時間</th>
  </tr>
  <% working_time_sum_sum = 0 %>
  <% working_desired_time_sum = 0 %>
  <% @working_time_sum.each do |id, wts| %>
    <% working_time_sum_sum += wts %>
    <tr>
      <td><%= User.find(id).name %></td>
      <td><%= working_desired_time = User.find(id).working_desired_time %>時間</td>
      <% working_desired_time_sum += working_desired_time %>
      <td><%= wts / 3600 %>時間</td>
    </tr>
  <% end %>
  <tr>
    <td>合計</td>
    <td><%= working_desired_time_sum %>時間</td>
    <td><%= working_time_sum_sum / 3600 %>時間</td>
  </tr>
</table>
</div>