config/routes.rb
Rails.application.routes.draw do
  get 'privacy_policy/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'top#index'
  get "/privacy_policy" => "privacy_policy#index"

  resources :login, only: [:new, :create]
  delete '/logout',  to: 'login#destroy'
  
  resources :stores, except: [:index] do
    post 'approve_staff/:user_id', action: 'approve_staff'
    resources :store_weekly_schedules, only: [:new, :create, :destroy]
    resources :store_month_schedules, only: [:index, :create, :destroy] do
      collection do
        get ':beginning/new', action: 'new'
      end
    end
    
    resources :shift_section, only: [:index, :new, :create, :destroy]
    resources :shifts, only: [:create, :destroy] do
      collection do
        post ':beginning/change_status/:status' => 'shift_section#change_status'
        get ':beginning/:ending/new', action: 'new'
        get ':date/:working_time_from/edit', action: 'edit'
        get ':beginning', action: 'index'
      end
    end
  end

  resources :users, only: [:show, :new, :create, :edit, :update] do
    resources :user_weekly_schedules, :user_unable_schedules, :affiliation_application, only: [:new, :create, :destroy]
    resources :user_unable_schedules, only: [:index, :create, :destroy] do
      collection do
        get ':beginning/new', action: 'new'
      end
    end
    resources :user_submissions, only: [:create, :destroy]
  end
end

app/models/shift_section.rb
class ShiftSection < ApplicationRecord
  belongs_to :store,  optional: true
  has_many :user_submissions, dependent: :destroy

  validates :beginning, uniqueness: { scope: [:store_id] }
  validates :ending, uniqueness: { scope: [:store_id] }
  validates :status, inclusion: { in: 0..3 }
  with_options presence: true do
    validates :store_id
    validates :beginning
    validates :ending
    validates :status
  end
  validate :date, :duplicate

  def date
    if beginning && ending && beginning >= ending
      errors.add(:beginning, "可能な日付に設定してください")
    end
  end

  def duplicate
    if beginning && ending
      shift_sections = Store.find_by(id: store_id).shift_sections
      shift_sections&.each do |shift_section|
        if shift_section.beginning < beginning && beginning <= shift_section.ending || \
          shift_section.beginning <= ending && ending < shift_section.ending 
          errors.add(:beginning, "重複しています。可能な日付を設定してください。")
          return
        end
      end
    end
  end
end

app/controllers/shift_section_controller.rb
class ShiftSectionController < ApplicationController
  before_action :store_staff, :store_independent, only: [:index]
  before_action :owner_permission, except: [:index]

  include ActiveModel::Attributes
  include ActiveRecord::AttributeAssignment
  attribute :beginning, :date
  attribute :ending, :date

  def shift_section_params
    params.require(:shift_section).permit(:beginning, :ending).merge(store_id: params[:store_id], status: 0)
  end

  def change_status
    shift_section = ShiftSection.find_by(store_id: params[:store_id], beginning: params[:beginning])
    shift_section.status = params[:status]
    shift_section.save
    redirect_to "/stores/#{params[:store_id]}/shifts/#{params[:beginning]}"
  end

  def index
    @store_shift_sections = ShiftSection.where(store_id: params[:store_id])
    @store = Store.find(params[:store_id])
  end

  def new
    @store = Store.find(params[:store_id])
    @shift_section = ShiftSection.new
    @shift_section_status_012 = ShiftSection.find_by(store_id: @store.id, status: 0..2)
  end

  def create
    @store = Store.find(params[:store_id])
    @shift_section = ShiftSection.new(shift_section_params)
    if @shift_section.save
      redirect_to "/stores/#{params[:store_id]}/store_month_schedules/#{@shift_section.beginning}/new"
    else
      render :new
    end
  end

  def destroy
    shift_section = ShiftSection.find(params[:id])
    shift_section.destroy
    redirect_to store_shift_section_index_path(params[:store_id])
  end
end

app/helpers/shift_section_helper.rb
module ShiftSectionHelper
end

app/helpers/shift_sections.rb
module ShiftSectionsHelper
end

app/helpers/shift_sections_helper.rb
module ShiftSectionsHelper
end

app/views/shift_section/index.html.erb
<h1>シフト一覧</h1>
<% @store_shift_sections.each do |store_shift_section| %>
  <%= link_to "#{store_shift_section.beginning}~#{store_shift_section.ending}", "/stores/#{params[:store_id]}/shifts/#{store_shift_section.beginning}" %>
  <% if store_shift_section.status == 0 %>
    <div class="inline">ストアスケジュール編集中</div>
  <% elsif store_shift_section.status == 1 %>
    <div class="inline">スタッフのシフト希望提出待ち</div>
  <% elsif store_shift_section.status == 2 %>
    <div class="inline">シフト作成中</div>
  <% elsif store_shift_section.status == 3 %>
    <div class="inline">完成</div>
  <% end %>
  <% if owner? %>
    <%= button_to "削除", store_shift_section_path(@store, store_shift_section), method: :delete, data: {confirm: "シフトを削除しますか？"} %>
  <% end %>
  <br>
<% end %>
<%= link_to "シフトを新たに作成する", new_store_shift_section_path(@store) %>

app/views/shift_section/new.html.erb
<% if @shift_section_status_012 %>
  <%= link_to "シフト一覧", store_shift_section_index_path %>
  <p>他のシフトを完成させるか、削除してから新しいシフトを作成してください。</p>
<% else %>
  <%= form_for [@store, @shift_section], url: store_shift_section_index_path(@store) do |f| %>
    <% @shift_section.errors.full_messages.each do |message| %>
      <div class="form-error">
        <%= message %>
      </div>
    <% end %>
    <h1>シフトを新たに作成する</h1>
    <h2>期間</h2>
      <%= f.date_select :beginning, {use_month_numbers: true} %>
      <p>から</p>
      <%= f.date_select :ending, {use_month_numbers: true} %>
      <%= f.submit "作成" %>
  <% end %>
<% end %>